# Generated by Django 6.0.5 on 2026-06-11 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beaches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('risk_increase', 'Aumento de risco'), ('risk_decrease', 'Redução de risco')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('reason_factors', models.JSONField(default=dict)),
                ('safety_tips', models.JSONField(default=list)),
                ('previous_risk_level', models.CharField(max_length=20)),
                ('current_risk_level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='beaches.beach')),
                ('nearest_safe_beach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safe_redirects', to='beaches.beach')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBeachSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='beaches.beach')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beach_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'beach')},
            },
        ),
    ]
