# Generated by Django 6.0.5 on 2026-05-19 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beaches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(max_length=20)),
                ('probability', models.FloatField()),
                ('explanation', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaches.beach')),
            ],
        ),
    ]
