# Generated by Django 6.0.5 on 2026-05-19 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beaches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OceanCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave_height', models.FloatField()),
                ('tide_level', models.FloatField()),
                ('water_temperature', models.FloatField(null=True)),
                ('moon_phase', models.CharField(max_length=50)),
                ('collected_at', models.DateTimeField()),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaches.beach')),
            ],
        ),
    ]
