# Generated by Django 6.0.5 on 2026-05-19 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beaches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('incident_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaches.beach')),
            ],
        ),
    ]
